#!/bin/bash

# This script restarts the PipeWire service for the current user.
# PipeWire is a server for handling audio and video streams on Linux.
# The script uses systemd's systemctl command to restart the service.

bash -c "systemctl --user restart pipewire"
